sudo: required
language: java
jdk: openjdk15
branches:
  only:
  - master
  - /^feature/.*$/
cache:
  directories:
    - $home/.m2/repository
script: mvn clean package
after_success:
  - mvn test jacoco:report
  - bash <(curl -Ls https://coverage.codacy.com/get.sh) report
before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export DOCKER_TAG=fashionid/kafka-cluster-manager:$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
  - echo "DOCKER_TAG is $DOCKER_TAG"
deploy:
  - provider: script
    skip_cleanup: true
    script: docker build -t $DOCKER_TAG . && docker push $DOCKER_TAG
    on:
      branch: master
